### ISSUE TITLE
Sometimes Travis CI times-out during compilation

### ISSUE THREAD

**Issue by frenata** [frenata/xaqt#17]
Even jacking the timeout up to 10 seconds, the build failed with a timeout evaluating Haskell. But then it didn't. Another time it threw a 5 second timeout evaluating Java. I can't provoke similar timeouts in my local development environment, so I'm tempted to write it off as a Travis issue, but there might be something else going on.

**Comment by asmr-hex** [comment]
@frenata yeah i have observed this on two consecutive travis builds (see [build 37](https://travis-ci.org/frenata/xaqt/builds/372439134) and [build 38](https://travis-ci.org/frenata/xaqt/builds/372439732)). It looks like the first two languages to be tested timeout and they are different each time (first javascript/go, then java/c++)...

**Comment by frenata** [comment]
When I ran into this before, normally asking Travis to try again resulted in a passing build.

Non-deterministic bugs...

If it's failing *every* time for you, that might make it easier to track down.

**Comment by frenata** [comment]
I wonder if it's related to the fact that the channel is unbuffered?

https://github.com/frenata/xaqt/blob/master/sandbox.go#L76

There's not really a *reason* for it to be in this scenario, it might as well have a buffer of one. I'm going to see if this small change will continue to provoke timeouts.

**Comment by frenata** [comment]
It's clearly breaking on *every* build for me now. I can't replicate locally though.

**Comment by frenata** [comment]
```
2018/04/28 17:41:00 sandbox launching sandbox...
Language: C#
Stdin: 
*-BRK-*
Code: Hidden
2018/04/28 17:41:00 wrote file /tmp/xaqt-829950777/script.sh
2018/04/28 17:41:00 wrote file /tmp/xaqt-829950777/javaRunner.sh
2018/04/28 17:41:00 wrote file /tmp/xaqt-829950777/create_user.sql
2018/04/28 17:41:00 wrote file /tmp/xaqt-829950777/sql_runner.sh
2018/04/28 17:41:00 wrote file /tmp/xaqt-829950777/destroy_user.sql
2018/04/28 17:41:00 finished copying payload
2018/04/28 17:41:00 writing inputfile: 
*-BRK-*
2018/04/28 17:41:00 go spawnDocker for mcs
2018/04/28 17:41:00 cmd executed, waiting for output from mcs
2018/04/28 17:41:10 mcs timed out
2018/04/28 17:41:11 sandbox run error: Timed out
< other stuff >
2018/04/28 17:41:26 got output from cmd from mcs
2018/04/28 17:41:26 Docker stdout: docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"/usercode/script.sh\": stat /usercode/script.sh: no such file or directory".
```

The above with some extra logging thrown in to better see what's happening and when. The hangup is happening here:

```
cmd := exec.Command(dockerCommand, args...)
log.Printf("cmd executed, waiting for output from %s", compiler)
bytes, err := cmd.CombinedOutput()
log.Printf("got output from cmd from %s", compiler)
```

While waiting for the results of `CombinedOutput()`.
